server {
    listen 80;
    server_name aibyjw.duckdns.org;
    return 301 https://$host$request_uri;
}
server {
    listen 443 ssl;
    server_name aibyjw.duckdns.org;
    ssl_certificate     /etc/letsencrypt/live/aibyjw.duckdns.org/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/aibyjw.duckdns.org/privkey.pem;
    ssl_protocols       TLSv1.2 TLSv1.3;
    client_max_body_size 25M;
    location / {
        proxy_pass         http://127.0.0.1:3001;
        proxy_http_version 1.1;
        proxy_set_header   Host $host;
        proxy_set_header   X-Real-IP $remote_addr;
        proxy_read_timeout 120s;
    }
}